Script started on Fri Aug  8 12:59:26 2014
[?1034hbash-3.2$ cd ..
bash-3.2$ ls
Makefile	src		tests
bash-3.2$ make
mkdir bin
g++  src/main.cpp  -o bin/rshell
bash-3.2$ bin/rshell
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -l
total 8
-rw-r--r--  1 RashidGoshtasbi  staff  168 Aug  7 11:50 Makefile
drwxr-xr-x  3 RashidGoshtasbi  staff  102 Aug  8 12:59 bin
drwxr-xr-x  5 RashidGoshtasbi  staff  170 Aug  8 12:59 src
drwxr-xr-x  3 RashidGoshtasbi  staff  102 Aug  8 12:59 tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a
.		.git		bin		tests
..		Makefile	src
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -l		-a
total 8
drwxr-xr-x   7 RashidGoshtasbi  staff  238 Aug  8 12:59 .
drwxr-xr-x   8 RashidGoshtasbi  staff  272 Aug  7 08:57 ..
drwxr-xr-x  15 RashidGoshtasbi  staff  510 Aug  8 12:44 .git
-rw-r--r--   1 RashidGoshtasbi  staff  168 Aug  7 11:50 Makefile
drwxr-xr-x   3 RashidGoshtasbi  staff  102 Aug  8 12:59 bin
drwxr-xr-x   5 RashidGoshtasbi  staff  170 Aug  8 12:59 src
drwxr-xr-x   3 RashidGoshtasbi  staff  102 Aug  8 12:59 tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a			-l
total 8
drwxr-xr-x   7 RashidGoshtasbi  staff  238 Aug  8 12:59 .
drwxr-xr-x   8 RashidGoshtasbi  staff  272 Aug  7 08:57 ..
drwxr-xr-x  15 RashidGoshtasbi  staff  510 Aug  8 12:44 .git
-rw-r--r--   1 RashidGoshtasbi  staff  168 Aug  7 11:50 Makefile
drwxr-xr-x   3 RashidGoshtasbi  staff  102 Aug  8 12:59 bin
drwxr-xr-x   5 RashidGoshtasbi  staff  170 Aug  8 12:59 src
drwxr-xr-x   3 RashidGoshtasbi  staff  102 Aug  8 12:59 tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a #test
.		.git		bin		tests
..		Makefile	src
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls #test
Makefile	bin		src		tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ #test
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a
.		.git		bin		tests
..		Makefile	src
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ 3test     #test
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ #test
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ #t  ls -a
.		.git		bin		tests
..		Makefile	src
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls
Makefile	bin		src		tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ clear
EXECLV FAILED: : No such file or directory
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -   a
ls: -: No such file or directory
ls: a: No such file or directory
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -  				-s
total 8
8 Makefile	0 bin		0 src		0 tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls a
ls: a: No such file or directory
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a
.		.git		bin		tests
..		Makefile	src
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a  		 				ia
ls: ia: No such file or directory
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ^[[A    ls -  			-a
.		.git		bin		tests
..		Makefile	src
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls 									-l
total 8
-rw-r--r--  1 RashidGoshtasbi  staff  168 Aug  7 11:50 Makefile
drwxr-xr-x  3 RashidGoshtasbi  staff  102 Aug  8 12:59 bin
drwxr-xr-x  5 RashidGoshtasbi  staff  170 Aug  8 12:59 src
drwxr-xr-x  3 RashidGoshtasbi  staff  102 Aug  8 12:59 tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ex  #te   te  @ #test shjows    ows that all combinations of ls -a - and plain ls   pu lus the pound sign works
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a &
.		.git		bin		tests
..		Makefile	src
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ ls -a&
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ .		.git		bin		tests
..		Makefile	src
ls -a								&
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ .		.git		bin		tests
..		Makefile	src
#also the andpersign o            & works as e well
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ #end of all variation of tests
RashidGoshtasbi@ucrwpa3-1-209-123.bulk.ucr.edu$ exit
bash-3.2$ ext[Kit
exit

Script done on Fri Aug  8 13:02:18 2014
